import "~/styles/globals.css";
import ThemeProvider from "~/providers/ThemeProvider";
import Particles from "~/components/Particles";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.15.4/css/all.min.css"
        />
      </head>
      <body className={`font-sans ${montserrat.variable}`}>
        <ThemeProvider>
          <Particles />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
